sighupio/gatekeeper-policy-manager

manifests/rbac.yaml
The service account has missing permissions for the GPM to be able to have read access to `config.gatekeeper.sh` apigroup. 
- Adding 
```
- apiGroups: ["config.gatekeeper.sh"]
resources: ["*"]
verbs: ["get", "list", "watch"]
```
=> Update RBAC policies

app/app.py, app/templates/base.html
The configs view gave a 404 error message when there were no configs CRDs on the cluster. Let's handle better that case and show that there are no configs instead of an error.
As a bonus fix the order of the JS scripts tags so we get rid of unwanted space in the toolbar.
=> configs view throws 404

.bumpversion.cfg, CHANGELOG.md, README.md, app/templates/footer.html, kustomization.yaml, manifests/rbac.yaml
Hi!
This PR includes a configuration file to use with bumpversion to easily release a new version just taking care about running the right bumpversion command:
```bash
$ bumpvesion patch
$ bumpvesion minor
$ bumpvesion major
```
Then
```bash
$ git push origin master --tags
```
It includes a small fix in the `ClusterRoleBinding` apiversion. (Spotted by deprek8ion).
Thanks!
=> Bumpversion config

app/requirements.txt
Reverts sighupio/gatekeeper-policy-manager#21
`astroid 2.4.2 has requirement lazy-object-proxy==1.4.*, but you'll have lazy-object-proxy 1.5.1 which is incompatible.`
=> Revert "Update dependency lazy-object-proxy to v1.5.1"

.drone.yml, tests/deploy-patch.yaml, tests/e2e-tests.yaml, tests/helper.bash, tests/kustomization.yaml, tests/tests.sh
Hi!
This PR adds an e2e testing pipeline.
~**Pending to create the final tests.**~
Currently, it provides all the components and structure to run e2e tests in an automatic manner.
Pipelines now have some conditions:
- License and Policeman runs always
- e2e Pipeline runs on `tags`, `master`, and `renovate` branches.
- Release pipeline runs on `tags` and `push` events excluding `renovate` branches.
This way, we can automate test renovate PRs.
=> Add automatic e2e tests

.drone.yml, tests/tests.sh
Hi @ralgozino 
This PR contains some improvements in the CI pipeline:
1. Increase timeout of the e2e tests
2. Add automatic release on GitHub (as we are currently doing with other SIGHUP software)
3. FIX an error with building from the cache
4. now, we build and test the same image we publish.
Thanks!
=> Add automatic release notes

app/uwsgi.ini
**Error :** 
```
invalid request block size: 5292 (max 4096)...skip
10.x.x.x - - [02/Nov/2020:08:33:43 +0000] "GET /favicon.ico HTTP/1.1" 502 560 "https://gpm.<redacted>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36" "10.x.x.x"
2020/11/02 08:33:43 [error] 10#10: *16 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.x.x.x.x, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock:", host: "gpm.<redacted>", referrer: "https://gpm.<redacted>/"
```
**Reason:** 
By default, uWSGI allocates a very small buffer (4096 bytes) for the headers of each request. If you start receiving “invalid request block size” in your logs, it could …
=> Update the uWSGI buffer size.

.drone.yml
Ciao Ramiro!
This PR contains a couple of improvements/fixes:
1. Avoid dockerhub rate limit on build step.
Seems like using just the socket is not enough to authenticate requests against dockerhub, so I have mounted the credentials into the `docker:dind` container that builds the application.
2. Improve and update the e2e pipeline.
Again, it runs on kind on top of `docker:dind` container image. I've mounted the credentials here too to avoid rate limits. Then, i've updated the `kind` binary and the `cluster version`. Finally, we use our own registry to pull the `kindest/node` image. Bonus: I've removed the `gunicorn` branch trigger from the e2e pipeline.
Let me know if everything looks fine to you.
=> Pipeline improvements

app/templates/constrainttemplates.html
At the moment if there are policy templates which doesn't have `properties` or are without defined `openAPIV3Schema` field, constrainttemplates page will fail with exception.
This PR is adding some check if above exists in the jinja template.
=> Fix correct handling of missing properties

manifests/deployment.yaml
If the replicas field is not explicitly set it
defaults to 1.
Although this doesn't seem to be a problem some
Gitops tools (e.g. flux) use 'kubectl apply -f'
under the hood and will not be able to reconcile
the state if someone manually scales down the
deployment and replicas are not explicitly set
=> Explicitly set the number of replicas

chart/Chart.yaml, chart/templates/ingress.yaml, chart/values.yaml
As mentioned in https://github.com/sighupio/gatekeeper-policy-manager/issues/361, the chart install currently breaks as the ingress v1beta1 APIs were deprecated from 1.22 onwards.
I did my best to replicate the current values.yaml behaviour in the new ingress template.
I updated the `Chart.yaml` with a minor version bump as well.
=> Update ingress template in helm chart to support k8s 1.22

app/app.py
Fixes #389 - handle the case when the OIDC session has expired.
For example, if it has been ended by the IDP. In that case, we redirect to the previous page, that then it re-requires the login.
=> fix: handle expired sessions

app/web-client/src/pages/ConstraintTemplates/Component.tsx
Fixes #379 ConstraintTemplates page should show description when available
Shows the contraint template description under the title when it's present
=> fix: show ConstraintTemplates description when available

app/app.py, app/web-client/src/pages/Constraints/Component.tsx
The download report button did not include the current context in the link, so the link was pointing to the default context always instead of the selected one when running in a multicluster scenario.
Fixes #456
=> Fix multicluster report download

app/web-client/src/pages/Constraints/Component.tsx
This PR introduces:
- stop truncating text in the Constraints' violations table.
- increase the width for the Constraints view to show more data on bigger screens. We left the other views on the previous width on purpose because the text paragraphs get too wide, but showing better the table makes it acceptable in the constraints view.
Fixes #455 
Here's a screenshot
=> Fix: improve constraint violations table

chart/values.yaml, manifests/deployment.yaml
Closes #542.
https://kubernetes.io/docs/concepts/security/pod-security-standards/
I made the changes directly in `values.yaml` since the template simply calls `{{- toYaml .Values.securityContext | nindent 12 }}`.
=> feat: comply with 'Restricted' Pod Security Standard

app/app.py, app/web-client/src/App.tsx, app/web-client/src/components/Header/Component.tsx
This PR drops the POST endpoint for `/logout` and uses only the GET endpoint to avoid CORS issues when logging out.
@Al-Pragliola  I'm not 100% sure why we were using the POST with fetch and then the GET. I did not find any regression in switching to just GET.
Fixes #725
=> fix: make one GET to /logout to avoid CORS issues

app/web-client/src/components/Header/Component.tsx
- Show tooltip whit the complete context name when hovering with the mouse pointer
- Drop the maximum width constraint
- Add placeholder text
- Add divider between options for clarity
Fixes #980
This branch is based on #981
=> fix: show tooltip for long context names

.gitignore, chart/Chart.yaml, chart/templates/deployment.yaml, chart/templates/secret.yaml, chart/values.yaml
Hello @ralgozino & @Al-Pragliola 
Right now you have to set the `config.secretKey` in Helm values **in plain text** to set the `GPM_SECRET_KEY` env var. I thought it would be beneficial to allow users to set the env var by referencing a secret that can be deployed separately.
To make this possible, I refactored the Helm Chart slightly. Now it's possible to set `config.secretRef` in Helm values. If this field is set (and `config.secretKey` is set to `null`), the `GPM_SECRET_KEY` env var in deployment is set from the custom secret (not the default one).
I have tested the changes in a production-grade k8s cluster.
=> Allow setting secret key by referencing a present/custom secret

.drone.yml
Our drone configuration stopped working when we added some more workers. We were abusing the pipelines to group steps together, but Drone runs each pipeline in a different worker without shared volumes, etc. So we can't use the image build in one worker in the other.
There does not seem to be an easy way of choosing to run the pipelines in the same worker, so we need to refactor all the pipelines.
=> chore(ci): fix CI definition for >1 workers

chart/templates/deployment.yaml
This PR makes it possible to pass the `GPM_SECRET_KEY` via `extraEnvs` to allow runtime secret injection eg. via Vault secrets webhook.
=> Modify deployment template to support passing GPM_SECRET_KEY as env var
